# Required by Hydra to know which function to use for the dataloader
# The import path is relative to the file which we run (in this case, estimate_lid.py)
_target_: data.utils.dataloaders.get_imagenet_dataloader

# Arguments for the ImageNet dataloader
root: /BS/databases23/imagenet/original/  # Path to the ImageNet dataset
split: val  # Dataset split, can be "train" or "val"
batch_size: 32  # Batch size for loading data
image_size: 256  # Image size for resizing and cropping
class_filter: null  # Optional list of class IDs to filter (null means no filtering)
num_workers: 64  # Number of workers for data loading
shuffle: false  # Whether to shuffle the data