train:
  _target_: data.datasets.HuggingFaceDataset

  dataset:
    # similar to datasets.load_dataset(path="mnist", split="train", trust_remote_code=True)
    _target_: datasets.load_dataset
    path: mnist # Huggingface dataset from https://huggingface.co/datasets
    split: train
    trust_remote_code: True

  transform: null # Leave this blank to inject later. this will be experiment specific.


val:
  _target_: data.datasets.HuggingFaceDataset

  dataset:
    _target_: datasets.load_dataset
    path: mnist # Huggingface dataset from https://huggingface.co/datasets
    split: test
    trust_remote_code: True

  transform: null # Leave this blank to inject later. this will be experiment specific.

