train:
  _target_: data.datasets.HuggingFaceDataset

  dataset:
    _target_: datasets.load_dataset
    path: mnist # Huggingface dataset from https://huggingface.co/datasets
    split: train
    trust_remote_code: True

  transform:
    _target_: torchvision.transforms.Compose
    transforms: ${_all_data_transforms}


val:
  _target_: data.datasets.HuggingFaceDataset

  dataset:
    _target_: datasets.load_dataset
    path: mnist # Huggingface dataset from https://huggingface.co/datasets
    split: test
    trust_remote_code: True

  transform:
    _target_: torchvision.transforms.Compose
    transforms: ${_all_data_transforms}

