# Normalizes the tensor to a standardized scale
# Neural networks (especially with batch norm or weight init) often assume inputs are centered around 0.
# x_normalized = (x - mean) / std
# This maps pixel values from [0.0, 1.0] to [-1.0, 1.0]

# Note that you can pass in a list of means and stds,
# and the transform will apply them to each channel of the image.
# For example, if you have a 3-channel RGB image, you can pass in:
#   mean: [0.5, 0.5, 0.5]
#   std: [0.5, 0.5, 0.5]
# So this is generic and can be used for any number of channels.
_target_: torchvision.transforms.Normalize
mean: ${experiment.dataset.mean}
std: ${experiment.dataset.std}
