out_dir: ./outputs # where to keep the logs

# "defaults" defines which configuration files should be merged together to create the full config tree.
defaults:
- experiment: ??? # the value of this key is set in the command line
- hydra: default
- dataset: ${dataset}
- model: ${model}
- _self_


train:
  device: cuda  # or "cpu"

  model: ${model}

  loader: 
    _target_: torch.utils.data.DataLoader
    dataset: ${dataset.train}
    batch_size: ${batch_size}
    shuffle: True
    num_workers: 40

  trainer: 
    max_epochs: ${max_epochs}

  ckpt_path: null

  optimizer:
    _target_: ${optimizer}

  loss:
    _target_: ${loss}
