# "defaults" defines which configuration files should be merged together to create the full config tree.

defaults:
- hydra: default
- dataset: cifar10
- dgm: diffusion
- _self_


train:
  dgm: ${dgm}

  loader: 
    batch_size: 128
    shuffle: True
    num_workers: 40

  val_loader:
    batch_size: 128
    num_workers: 40

  trainer: 
    max_epochs: 1000

  ckpt_path: null
