out_dir: ./output_hev
# "defaults" defines which configuration files should be merged together to create the full config tree.
defaults:
- experiment: ??? # the value of this key is set in the command line
- _self_


train:
  device: cuda  # or "cpu"

  loader: 
    _target_: torch.utils.data.DataLoader
    dataset: ${experiment.dataset.train}
    batch_size: ${experiment.batch_size}
    shuffle: True
    num_workers: 40
    pin_memory: True

  trainer: 
    max_epochs: ${experiment.max_epochs}

  ckpt_path: null

  optimizer:
    _target_: ${experiment.optimizer}

  loss:
    _target_: ${experiment.loss}


wandb:
  # If you want to use wandb, set this to true.
  enable: false
  project: "thesis_hev"
  run_name: "${experiment.experiment_name}_${now:%Y-%m-%d_%H-%M-%S}"
  mode: online  # or "offline" if no internet
