defaults:
  - /model: MLPUnet
  - /sde: VpSDE
  - _self_



all_sampling_transforms:
  t0: data_transforms.unflatten_1_28_28
  t1: data_transforms.inverse_normalize_mnist

sampling_transforms:
  _target_: torchvision.transforms.Compose
  transforms: ${oc.dict.values:..all_sampling_transforms}
  

checkpoint_path: outputs/hydra/mnist/checkpoints/latest.pt

sample_name: mnist_sample

num_samples: 16
sample_shape: [1, 28, 28]
timesteps: 1000
batch_size: 128

data_dim: 784

