# conf/model/token_count_predictor.yaml
_target_: models.heuristic_token_count_predictor.HeuristicTokenCountPredictor

# MLP
hidden_dims: []            # [] => no hidden layers
hidden_activation: sigmoid    # relu | gelu | silu | tanh
dropout: 0.1               # applied after each hidden layer (if any)

# Output head
output_activation: sigmoid # linear | sigmoid | relu | softplus
output_min: 1.0            # only used when output_activation == sigmoid
output_max: 256.0