# conf/model/token_count_predictor.yaml
# Heuristic token-count predictor (MLP) configuration
# Maps heuristic features (e.g., [edge_ratio, vgg_error]) -> token count.

# Module to instantiate
_target_: models.heuristic_token_count_predictor.HeuristicTokenCountPredictor

# -----------------------------
# Input feature dimensionality
# - 2 for [edge_ratio, vgg_error]
# - 1 if only a single scalar feature is used
num_additional_features: 0
num_classes: 256
hidden_dim: 32

# -----------------------------
# Input normalization options
# use_log1p_recon: apply log(1 + x) to reconstruction loss to compress dynamic range
# normalize_inputs: apply BatchNorm1d to all inputs for consistent scaling
use_log1p_recon: true
normalize_inputs: true


