# conf/model/token_count_predictor.yaml
_target_: models.neural_token_count_predictor.NeuralTokenCountPredictor

# --- VAE ---
hf_hub_path: stabilityai/sd-vae-ft-mse
freeze_vae: true

# --- Classification head ---
num_classes: 256            # counts 1..256
pooling: gap                # 'gap' (default) or 'flatten'
feature_dim: null           # ONLY set if pooling: flatten (e.g., 4096 for 256x256 with SD-VAE)

# --- Conditioning vector ---
loss_dim: 1                 # tolerated loss is a single scalar; increase if you add more features

# --- MLP design ---
hidden_dims: []  # make [] to use a single Linear(in_dim -> num_classes)
activation: gelu                  # relu | gelu | silu | tanh
dropout: 0.1
